version: '3'

services:
  docker:
    image: docker:24-dind
    command: dockerd --host=unix:///var/run/docker.sock --tls=false --host=tcp://0.0.0.0:2376
    # Privileged mode is required for DinD.
    privileged: true
    networks:
      - runner-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "docker", "ps"]
      interval: 3s
    volumes:
      - docker-data:/var/lib/docker
    # Remove the labels to disable auto updates
    labels:
      - com.centurylinklabs.watchtower.scope=actions-runner

  worker:
    # You can change the tag for runner image
    image: myoung34/github-runner:latest
    env_file: .env
    networks:
      - runner-network
    restart: unless-stopped
    depends_on:
      docker:
        condition: service_healthy
    # Don't change these environment var, it is required for runner container to communicate with Docker daemon
    environment:
      - DOCKER_HOST=tcp://docker:2376
    # Remove the labels to disable auto updates
    labels:
      - com.centurylinklabs.watchtower.scope=actions-runner
    # Change the number replicas as you liked, please use EPHEMERAL option in .env if you do this.
    deploy:
      replicas: 8

networks:
  runner-network:

volumes:
  docker-data:
